name: Build and Package Kivy App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip unzip libffi-dev libssl-dev

    - name: Install buildozer
      run: |
        python -m pip install --upgrade pip
        python -m pip install buildozer cython

    - name: Create directories for Android SDK command line tools
      run: |
        mkdir -p $HOME/.buildozer/android-sdk/cmdline-tools

    - name: Download Android SDK command line tools
      run: |
        curl -O https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip
        unzip commandlinetools-linux-6609375_latest.zip -d $HOME/.buildozer/android-sdk/cmdline-tools
        mv $HOME/.buildozer/android-sdk/cmdline-tools/cmdline-tools $HOME/.buildozer/android-sdk/cmdline-tools/tools

    - name: Build Kivy app
      run: |
        buildozer -v android debug
