name: Build Kivy Android APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools cython virtualenv
        pip install buildozer

    - name: Download Android SDK
      run: |
        mkdir -p $HOME/.buildozer/android-sdk/cmdline-tools
        curl -L -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip
        unzip commandlinetools.zip -d $HOME/.buildozer/android-sdk/cmdline-tools
        mkdir -p $HOME/.buildozer/android-sdk/cmdline-tools/tools

    - name: Move SDK files
      run: |
        mv $HOME/.buildozer/android-sdk/cmdline-tools/*/* $HOME/.buildozer/android-sdk/cmdline-tools/tools || echo "No files to move"

    - name: Accept SDK Licenses
      run: |
        yes | $HOME/.buildozer/android-sdk/cmdline-tools/tools/bin/sdkmanager --licenses
        $HOME/.buildozer/android-sdk/cmdline-tools/tools/bin/sdkmanager --update

    - name: Install Build Tools
      run: |
        $HOME/.buildozer/android-sdk/cmdline-tools/tools/bin/sdkmanager "build-tools;35.0.0" --licenses

    - name: Create buildozer.spec
      run: |
        echo "[app]" > buildozer.spec
        echo "title = My Application" >> buildozer.spec
        echo "package.name = chat-ai" >> buildozer.spec
        echo "package.domain = org.myapp" >> buildozer.spec
        echo "source.dir = ." >> buildozer.spec
        echo "source.include_exts = py,png,jpg,kv,atlas" >> buildozer.spec
        echo "version = 1.0" >> buildozer.spec
        echo "requirements = python3, kivy, google-generativeai, arabic-reshape, bidi" >> buildozer.spec
        echo "android.permissions = INTERNET, ACCESS_NETWORK_STATE" >> buildozer.spec
        echo "android.ndk = 19b" >> buildozer.spec
        echo "android.api = 29" >> buildozer.spec
        echo "android.minapi = 21" >> buildozer.spec
        echo "source.main = main.py" >> buildozer.spec
        echo "android.sign = False" >> buildozer.spec
        echo "source.include_assets = assets" >> buildozer.spec

    - name: Build APK
      run: buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: chat-ai-apk
        path: .buildozer/android/platform/build/dists/chat-ai/build/outputs/apk/debug/*.apk
